### ISSUE TITLE
SwiftPublicSuffixList dependancy issue

### ISSUE THREAD

**Issue by rondyck** [ekscrypto/SwiftEmailValidator#8]
After installing the `SwiftEmailValidator` package via the Xcode's package dependency tool, I get the following error:
`The package product 'SwiftPublicSuffixList' requires minimum platform version 11.0 for the iOS platform, but this target supports 9.0`

My iOS Deployment Target is 15.0, the SwiftPublicSuffixList Package.swift file shows the iOS requirement of v11.

Am I missing something here?

Thanks,
Ron Dyck

**Comment by ekscrypto** [comment]
It looks like your target or your project is configured for iOS 9.0.  There are two applicable settings in Xcode, one at the project level and one at a target level.  Make sure both are set to the iOS version you want to support and you should be fine.

**Comment by rondyck** [comment]
Hi @ekscrypto 

Sorry for any lack of understanding here, but as shown in attached screenshots, I believe I have both Project and Target set for iOS 15.0

Please advise.

<img width="727" alt="Screen Shot 2022-03-25 at 08 56 45" src="https://user-images.githubusercontent.com/23153194/160124786-3e65a93b-4ccb-40b7-9fbf-a6560b37c904.png">
<img width="664" alt="Screen Shot 2022-03-25 at 08 57 47" src="https://user-images.githubusercontent.com/23153194/160124948-3a1bdfdf-01c4-41e7-8510-55d3a7ce8235.png">

**Comment by ekscrypto** [comment]
Did you check that your unit tests and other services are also set to 15.0 ?

**Comment by ekscrypto** [comment]
Please re-open this issue if it's still a problem.  I couldn't reproduce the issue in my sample projects.

**Comment by ekscrypto** [comment]
@rondyck I believe I identified & fixed the source of the issue.  Can you try again with version 1.0.1 ?
